fix all DIRT graphical errors:
fix glitches textures flickering fix textures on car hubcaps etc.
and enjoy it until tomorrow it comes out now but I won't even be able to try it until tomorrow because I have school
