Xbox Community Guidelines
We've built Xbox for people like you, for gamers of all kinds around the world who want the same thing: a place to play and have fun. We need your help to keep the Xbox community safe and fun for everyone.

While the Code of Conduct section of the Microsoft Services Agreement applies to all Microsoft products, Xbox offers so many ways to interact with others that it deserves some additional explanation.

To this end, we have created the following Xbox Community Guidelines. Consider these standards as a roadmap for contributing to this amazing community that spans the globe. Remember: the Xbox community is yours. We all bring something unique, and that uniqueness is worth protecting.

Whether you're new to gaming or have been gaming for decades, we need all of you to be stewards of this place, protecting each other, even when you compete. Because when we all play, we all win.

Content
Our shared values

Conduct

Content

Attitude

Cross-platform game

Rules

i. Keep the law

ii. Do your part to protect everyone

iii. Convert unwanted content into substance content

IV. Keep the content clean

v. Fraud benefits no one

saw. When there are limits, there is a reason for it

vii. Disruptive behavior has no place on Xbox

viii. Respect the rights of others

ix. Always respect the privacy of others

x. Be a force for good, even when others are not

Impact

Our shared values
The spirit of Xbox lies in our values, which are the key to maintaining a vibrant and welcoming community. Living these values ​​every time we play shows the world the unifying power of gaming.

Everyone can enjoy the games
Creativity drives the community
Competition is better when it's fair
Helping others makes us all stronger
Hate has no place here
Conduct
Some parts of the internet don't have rules, but the Xbox community does. Yes, Xbox is, in a sense, your gaming network. But it also belongs to millions of people. You deserve a place to be yourself with confidence, free from intimidation, hate and harassment, just like any other gamer. So it is important to treat others as you would like to be treated.

Remember:

Win or lose, be a good competitor
Did anyone have a great game? Let him know!
you are the community
Some criticism is fine, but keep it clean
Nobody likes trolls so don't be one
Content
Gamertags, gamerpics, screenshots, game clips, and other posts you make on Xbox can be a great way to highlight what's important to you. We encourage all players to be themselves and show what they like, what makes them laugh, or what makes them awesome. But this exchange cannot be done at the expense of the positive experiences of other players.

Remember:

Use your skills and creativity to add informative, useful, fun, or interesting content that makes a positive contribution to our vibrant and diverse community.
The content you post should be suitable for a wide audience
Context is important, and mature content that makes sense in one game may not be appropriate elsewhere in the Xbox community.
Not everyone has the same likes or dislikes as you, so think twice before saying anything detrimental about someone else's content, play style, or choices.
Attitude
Helping others makes us stronger. If you want to be a superstar and live our shared values, here are some ways to go above and beyond:

Help others have a great gaming experience by joining Xbox Ambassadors
Do you know a great community leader? Nominate him for the Xbox MVP Award
Hang out with like-minded gamers by joining clubs
Make new friends by creating Hunt Parties to join others in your favorite game
If you see or witness inappropriate content or behavior, we recommend that you mute, block, and report players who are acting inappropriately
Cross-platform game
At Xbox, PlayStation and Nintendo we believe that video games are a force that unites the world. Cross-platform play allows players from all platforms to participate in a connected community that spans the globe. No matter where you play from, we invite you to join. Remember that when we come together, we are all players and have a role to play in helping others level up:

Remember:

You must be a positive ambassador of the platform.
It welcomes all players to encourage healthy competition across platforms.
Having a great love for the platform is very good, but respect the place from which
Más información sobre este texto de origenPara obtener más información sobre la traducción, se necesita el texto de origen
Enviar comentarios
Paneles laterales
Historial
Guardado
Contribuir
Rules
If you've read the Microsoft Services Agreement, the following rules are probably familiar to you. This may sound like legal jargon, but bear with us - enforcing these rules is essential to maintaining a community where everyone can have fun. People differ on what looks like fun, and sometimes there are conflicts. But while there are many conflicts that can be resolved between players, there are some things that we cannot tolerate.

In each section, you'll find examples that show the relationship between the Microsoft Services Agreement Code of Conduct and Xbox Live.

i. Keep the law
Xbox is available in countries around the world, and it's important that people of all backgrounds feel safe and comfortable on our platform. To help ensure this, we must respect local laws and remove content or behavior that drives or promotes illegal activities.


For example, don't do the following:

ii. Do your part to protect everyone
To keep Xbox a place where everyone can have fun, we can't allow behavior or content designed to exploit, harm, or threaten anyone, regardless of age. When threatening, abusive, or insulting language is used against another member of our community, or the community at large, it undermines every player's ability to have fun.


For example, don't do the following:

iii. Convert unwanted content into substance content
It's great to be excited about your rise in popularity and to share all the great things you do on Xbox. The best way to do this is by producing amazing content, not through giveaways, asking people to like and follow you, or other inauthentic behavior. The best way to gain followers is by being yourself and creating awesome content that is uniquely yours. Remember... creativity drives community.


For example, don't do the following:

IV. Keep the content clean
People enjoy content of many types and styles on Xbox. Every taste is different, and that's great! However, that does not mean that absolutely anything goes. For the Xbox community to be a welcoming and inclusive place for everyone, some types of content need to be avoided.

Support a welcoming and inclusive community

Harassment and hate can take many forms, none of which have a place here. In order for the Xbox community to be a place where everyone can enjoy themselves, and to prevent people from feeling uncomfortable or unwelcome, we all need to do our part. This means more than just not harassing other players... it means embracing them. This involves saving the nasty jokes for people you know will enjoy them. It means taking special care of others while playing the game, considering how other people might interpret your content.


For example, don't do the following:

Know the difference between criticism and bullying

We understand: games can be competitive and interactions with other players can be intense. Criticism is an expected part of competitive multiplayer action, and that's not a bad thing. However, hate has no place here, and what is wrong is when such criticism turns into harassment.

Criticism includes jokes or bragging that focuses on the game at hand and encourages healthy competition. Harassment includes any negative behavior that is personalized, disruptive, or may make someone feel unwelcome or unsafe. To qualify as harassment, the behavior does not have to be prolonged or persistent. Even a single abusive message could damage someone's experience. I know when to draw the line and when to back down. Know and respect the other player.


For example:

Be yourself, but not at the expense of others

The Xbox community is yours, but also everyone else's. We encourage you to showcase what makes you unique and awesome, but it's not okay to post something that prevents others from having positive experiences. We aspire to a community where the game can be enjoyed by everyone. Problematic content gets in the way. If you're looking for a place on the internet that's too risque or goads people on, Xbox isn't the place for you.


For example, don't do the following:

Create content that is suitable for all audiences

Xbox is played by people from all over the world, and we understand that depending on their backgrounds, people have different perspectives on adult topics. However, since the Xbox community is meant to be welcoming and accessible to everyone, this is not the place for sexual content. Keep your posts and messages age-appropriate so this place is welcoming to everyone.


For example, don't do the following:

They will see what you did there

Sometimes at
